### ISSUE TITLE
Move repo to materials-marketplace

### ISSUE THREAD

**Issue by unkcpz** [unkcpz/hpc-app#3]
@pablo-de-andres @csadorf @yoavnash 
I should ask for your permission beforehand, I didn't know that I can directly do this 🤣, let me know if you want to make this repo private.

**Comment by unkcpz** [comment]
I make some large refactoring for both CSCS deployment (`cscs` branch) and IWM cluster deployment (`main` branch). 
They should be in one but I think I don't have time before the consortium meeting. 
A more thorough documentation on how to use and how to deploy is in the `README.md` file of `cscs` branch. I think that branch better be the default branch but I don't have permission to do that. Fell free to do it if any of you agree.

**Comment by csadorf** [comment]
@unkcpz Do you want me to change the default branch to `cscs`? Why not just merge into `main`?

**Comment by unkcpz** [comment]
>  Why not just merge into main?

Emm... I am the idiot. why didn't I think about this? I'll change the branch name `main` -> `iwm` and `cscs` -> `main`

**Comment by csadorf** [comment]
> > Why not just merge into main?
> 
> Emm... I am the idiot. why didn't I think about this? I'll change the branch name `main` -> `iwm` and `cscs` -> `main`

No, you are not. ❤️
